Update UI/1.5.0
epicmaxco/vuestic-admin pull request #893
Opened 2022-10-10 21:34 UTC by Azgiliat

2022-10-18 11:34 UTC, m0ksem requested changes
Review still in progress, but:

App.vue: we can remove following code, because:
1. There is no `--va-background` color anymore.
2. Page background is handled by vuestic-ui color service.
```
background: var(--va-background);
```

2022-10-18 11:34 UTC, m0ksem commented on src/services/vuestic-ui/themes.ts
>        warning: '#ffd43a',
We lost here dark background colors. So dark theme isn't really dark now. Consider adding here backgroundPrimary, backgroundSecondary etc. colors.

2022-10-18 11:34 UTC, m0ksem commented on src/services/vuestic-ui/themes.ts
>      },
We also lost VaSidebar color.
Previously we had `component: { VaSidebar: { color: 'coolBlueColor' } }`. Checkout master as reference.

2022-10-18 11:34 UTC, m0ksem commented on src/services/vuestic-ui/themes.ts
>  ]
@m0ksem, after we move useTheme to useColors in vuestic-ui we must remove useTheme from vuestic-admin.

2022-10-21 14:29 UTC, m0ksem requested changes

2022-10-21 14:29 UTC, m0ksem commented on src/components/maps/LineMap.vue
> +      stroke: am5.color(getColor(themeColors.value.variables?.primary)),
getColor('primary')

or themeColors.value.variables.primary

One of this way to get color, do not combine them.

2022-10-21 14:29 UTC, m0ksem commented on src/components/navbar/Navbar.vue
> +    background: red;
?

2022-10-21 14:29 UTC, m0ksem commented on src/components/navbar/Navbar.vue
> +      margin-right: 0.5rem;
Prefer mr-2 class

2022-10-21 14:29 UTC, m0ksem commented on src/components/navbar/components/dropdowns/MessageDropdown.vue
> +  <va-dropdown v-model="showDropdown" class="message-dropdown" position="bottom" :offset="[13, 0]">
Drop-downs are stateful by default. At least in latest version.

2022-10-21 14:29 UTC, m0ksem commented on src/pages/admin/dashboard/DashboardInfoBlock.vue
> +                  <p class="va-h2 va-text-center" :style="{ color: colors.info }">24</p>
Why do we use va-h2 on p tag instead of h2?

2022-10-21 14:29 UTC, m0ksem commented on src/pages/admin/dashboard/DashboardInfoBlock.vue
> +  .va-h2 {
Prefer ma-0 helper

2022-10-21 14:29 UTC, m0ksem commented on src/pages/admin/dashboard/DashboardInfoBlock.vue
> +  .va-h2 {
Line height must go away maybe?

2022-10-21 14:29 UTC, m0ksem commented on src/pages/admin/dashboard/dashboard-tabs/BankDetailsTab.vue
> +    padding-top: 0;
py-0

2022-11-01 13:01 UTC, asvae commented on package.json
>      "vue-i18n": "^9.1.10",
<img width="983" alt="image" src="https://user-images.githubusercontent.com/5394573/199238324-d5540e0c-c290-42cc-bc4e-7e78e38c3687.png">

2022-11-01 13:02 UTC, asvae commented on package.json
>      "vue-yandex-maps": "^0.12.3",
![image](https://user-images.githubusercontent.com/5394573/199238455-2a8b991f-f25f-416e-be76-c4b8126955cb.png)

2022-11-01 13:03 UTC, asvae commented on package.json
> -    "vuestic-ui": "^1.4.13"
![image](https://user-images.githubusercontent.com/5394573/199238904-2013d03e-598e-409d-be49-a49763cdc8c0.png)

2022-11-01 13:04 UTC, asvae commented on package.json
> -    "vuestic-ui": "^1.4.13"
![image](https://user-images.githubusercontent.com/5394573/199238904-2013d03e-598e-409d-be49-a49763cdc8c0.png)

2022-11-01 22:23 UTC, asvae approved these changes
Looks good. Thanks!

2022-11-01 22:24 UTC, merged