Tailwind CSS integration
epicmaxco/vuestic-admin pull request #903
Opened 2023-02-10 09:52 UTC by aluarius

## Description
- [x] Vuestic UI version bump to 1.6.0alpa.
- [x] Removed Vuestic UI grid CSS from imports.
- [x] Added Tailwind CSS.
- [x] All Vuestic UI helpers moved to Tailwind CSS.  
- [x] Related refactor and minor bugfixing. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2023-02-10 22:17 UTC, m0ksem requested changes

2023-02-10 22:17 UTC, m0ksem commented on README.md
> +  <a href="https://vuejs.org/partners/epicmax.html" target="_blank" title="VueJS - The Progressive JavaScript Framework">
Junk?

2023-02-24 16:22 UTC, aluarius commented
> Lost some icons

Icon's color. It was before - didn't mention. Fixed.

About second screenshot - can't repro via two browsers and deps reinstallation. Please, check if it wasn't accidentally for you.

<img width="749" alt="image" src="https://user-images.githubusercontent.com/64714442/221230437-4e782e13-21e6-4442-a296-5cd57f207bf6.png">

2023-02-24 19:41 UTC, m0ksem commented
@aluarius, try firefox

2023-02-27 08:26 UTC, aluarius commented
@m0ksem ah, i see, fixed.

2023-03-05 21:58 UTC, m0ksem approved these changes

2023-03-05 22:01 UTC, merged